# Generated by Django 4.2.27 on 2026-01-26 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_congelado', models.DecimalField(decimal_places=2, help_text='Precio al momento de usarlo', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SPLIT', 'Aire Acondicionado Split'), ('VENTANA', 'Aire Acondicionado Ventana'), ('HELADERA', 'Heladera Familiar'), ('COMERCIAL', 'Heladera Comercial/Exhibidora'), ('LAVARROPAS', 'Lavarropas')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('ubicacion', models.CharField(help_text='Ej: Dormitorio Principal', max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('DIAGNOSTICO', 'En Diagnóstico'), ('ESPERA', 'Esperando Repuesto/Aprobación'), ('REPARACION', 'En Reparación'), ('TERMINADO', 'Terminado (Listo p/ entregar)'), ('ENTREGADO', 'Entregado al Cliente')], default='PENDIENTE', max_length=20)),
                ('falla_declarada', models.TextField(help_text='Qué dijo el cliente que pasa')),
                ('diagnostico_tecnico', models.TextField(blank=True)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.equipo')),
                ('insumos', models.ManyToManyField(through='gestion.DetalleInsumo', to='gestion.producto')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestion.ordenreparacion')),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_tipo', models.CharField(help_text='Ej: R410a', max_length=20)),
                ('gas_cantidad', models.IntegerField(help_text='Carga en gramos')),
                ('datos_electricos', models.TextField(blank=True, help_text='Datos del compresor, capacitor, etc.')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='gestion.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='detalleinsumo',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ordenreparacion'),
        ),
        migrations.AddField(
            model_name='detalleinsumo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.producto'),
        ),
    ]
