# Generated by Django 4.2.27 on 2026-03-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_fotoequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenreparacion',
            name='en_banco_pruebas',
            field=models.BooleanField(default=False, help_text='Activa el panel SCADA para este equipo'),
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='estado_pago',
            field=models.CharField(choices=[('DEBE', 'Impago'), ('SENA', 'Seña / Anticipo'), ('PAGADO', 'Pagado Totalmente')], default='DEBE', max_length=20),
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='sena_monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto dejado a cuenta', max_digits=10),
        ),
    ]
