# Generated by Django 4.2.27 on 2026-03-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_ordenreparacion_en_banco_pruebas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='capacidad',
            field=models.CharField(blank=True, help_text='Ej: 3000 Frigorías, 400 Litros', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='costo_insumos_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='detalle_insumos_extra',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='reparacion_realizada',
            field=models.TextField(blank=True),
        ),
    ]
