# Generated by Django 4.2.27 on 2026-03-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_equipo_capacidad_ordenreparacion_costo_insumos_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='tipo_gas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Gas (Solo si aplica)'),
        ),
    ]
