# Generated by Django 4.2.27 on 2026-04-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_equipo_tipo_gas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenreparacion',
            name='detalle_insumos_extra',
            field=models.TextField(blank=True, help_text='Detalle rápido de insumos sin stock'),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='sena_monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto dejado a cuenta para comprar insumo o repuesto', max_digits=10),
        ),
    ]
