# Generated by Django 4.2.27 on 2026-04-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_ordenreparacion_detalle_insumos_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='gas_cantidad',
            field=models.IntegerField(blank=True, help_text='Carga en gramos', null=True),
        ),
    ]
