# Generated by Django 4.2.27 on 2026-04-03 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_fichatecnica_gas_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenreparacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DIAGNOSTICO', 'Diagnóstico'), ('REPARACION', 'Reparación'), ('COMPLETADO', 'Completado'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TURNO', 'Turno / Visita'), ('ENTREGA', 'Entrega de Equipo'), ('ALERTA', 'Alerta / Recordatorio')], max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('titulo', models.CharField(help_text='Ej: Visita a domicilio, Entrega Heladera', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='gestion.ordenreparacion')),
            ],
        ),
    ]
