# Generated by Django 5.2.17 on 2026-08-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_ordenreparacion_estado_eventocalendario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('SPLIT', 'Aire Acondicionado Split'), ('VENTANA', 'Aire Acondicionado Ventana'), ('HELADERA', 'Heladera Familiar'), ('COMERCIAL', 'Heladera Comercial/Exhibidora'), ('CAMARA', 'Cámara Frigorífica'), ('LAVARROPAS', 'Lavarropas')], max_length=20),
        ),
    ]
