# Generated by Django 5.2.17 on 2026-09-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_equipo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_operador', models.CharField(default='', max_length=100)),
                ('pin_firma_digital', models.CharField(blank=True, default='', max_length=50)),
                ('rol_posicion', models.CharField(default='Administrador del Sistema', max_length=100)),
                ('id_operador', models.CharField(default='OP-001', max_length=50)),
                ('nivel_acceso', models.CharField(default='SUPERUSUARIO', max_length=50)),
                ('token_valido_horas', models.IntegerField(default=24)),
                ('unidades_presion', models.CharField(choices=[('PSI', 'PSI'), ('Bar', 'Bar'), ('kPa', 'kPa'), ('kg/cm²', 'kg/cm²')], default='PSI', max_length=20)),
                ('unidades_temperatura', models.CharField(choices=[('°C', '°C'), ('°F', '°F'), ('K', 'K')], default='°C', max_length=20)),
                ('temp_max_adv', models.DecimalField(decimal_places=1, default=35.0, max_digits=6)),
                ('temp_max_crit', models.DecimalField(decimal_places=1, default=45.0, max_digits=6)),
                ('pres_max_adv', models.DecimalField(decimal_places=1, default=350.0, max_digits=6)),
                ('pres_max_crit', models.DecimalField(decimal_places=1, default=450.0, max_digits=6)),
                ('valor_hora_tecnica_usd', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('tipo_cambio_usd_ars', models.DecimalField(decimal_places=2, default=1200.0, max_digits=10)),
                ('margen_ganancia_sugerido', models.DecimalField(decimal_places=1, default=30.0, max_digits=5)),
                ('tarifa_diagnostico_usd', models.DecimalField(decimal_places=2, default=25.0, max_digits=8)),
                ('tarifa_mantenimiento_usd', models.DecimalField(decimal_places=2, default=40.0, max_digits=8)),
                ('multiplicador_urgencia', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
    ]
