# Generated by Django 5.2.17 on 2026-09-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('SPLIT', 'Aire Acondicionado Split'), ('VENTANA', 'Aire Acondicionado Ventana'), ('HELADERA', 'Heladera Familiar'), ('COMERCIAL', 'Heladera Comercial/Exhibidora'), ('CAMARA', 'Cámara Frigorífica'), ('LAVARROPAS', 'Lavarropas'), ('COMPRESOR_SEMI', 'Compresor Semihermético'), ('COMPRESOR_TORNILLO', 'Compresor Tornillo (Screw)')], max_length=20),
        ),
    ]
