# Generated by Django 5.2.17 on 2026-09-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_cliente_contacto_cliente_cuit_cliente_notas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('mensaje', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('CRITICO', 'Crítico'), ('ADVERTENCIA', 'Advertencia'), ('INFO', 'Info')], default='INFO', max_length=20)),
                ('atendida', models.BooleanField(default=False)),
                ('origen', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Alarma',
                'verbose_name_plural': 'Alarmas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
