# Generated by Django 4.2.27 on 2026-01-26 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.CharField(help_text='Ej: temp_salida, amperaje_compresor', max_length=50)),
                ('valor', models.FloatField()),
                ('unidad', models.CharField(max_length=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ordenreparacion')),
            ],
        ),
    ]
